### ISSUE TITLE
Get ADA equivalent of arbitraged non-ada token from price feed to determine profitability when dealing non-ADA pairs

### ISSUE THREAD

**Issue by sourabhxyz** [geniusyield/smart-order-router#114]
With the support of non-ADA pairs, bot would have to arbitrage solely in non-ADA tokens. In such case, it is important to know ADA equivalent of arbitraged token to know if it compensates ADA lost due to network tx fees.

**Comment by vjk0** [comment]
Do you mean an external price feed or the CNT/ADA orderbooks that we have available? The most convenient would be to have an option to first calculate the profit based on the best available price in the CNT/ADA orderbook and then (if profitable) do the actual token-to-ADA swap in the same transaction, resulting in pure ADA output.
