### ISSUE TITLE
SOR functioning

### ISSUE THREAD

**Issue by Vu-Frontcell** [geniusyield/smart-order-router#52]
Hi, This is a question geared more towards how SORs are functioning. Hope it's ok to post it here. I have been playing with the smart-order-routers and managed to locally build and run it according the documentation on GitHub. It seems to work but I'm a little bit puzzled. 

The sell and buy orders in the orderbook seems not to match the orderbook on the web site (by web site i mean the genius yield dex). First I thought that maybe the are some people interacting directly with the smart contract and bypass the web site, but then I put in an order myself on the web site but the order is not reflected in the order book in the SOR. 

For example lets look at the CRU/ADA pair. According to the log output -> MultiAsset Order Book Info: [{"commodityAsset":"432f429b1369039d55cfd0441267ca8a9ec4d696215ac0da009b74ec.74435255","currencyAsset":"lovelace"},[8,35]]

There is a total of 8 sell orders and 35 buy order but if you look at the web site it is total different. I'm worried that there is something fundamental that I'm missing about the SORs. If someone can shed some light I would appreciate it very much.

**Comment by Vu-Frontcell** [comment]
Ah, I wasn't aware of that. Thanks for the info. 
If updating just involves to change some config values maybe I can change it locally on my machine? If you can provide the values or direct me where I can get those.

Please bear with me. I'm not so knowledgable about cardano blockchain and learning I'm Haskell in the go as needed so the learning curve is quite steep.

**Comment by sourabhxyz** [comment]
Don't worry, we'll have this repo updated, along with improved documentation by ~Tuesday.

**Comment by sourabhxyz** [comment]
Done by #54.
