### ISSUE TITLE
To not consider tx fees when currency is lovelace in determination of whether bot is loosing money or not

### ISSUE THREAD

**Issue by sourabhxyz** [geniusyield/smart-order-router#62]

**Comment by 4TT1L4** [comment]
Duplicate of https://github.com/geniusyield/smart-order-router/issues/65 which is a bug report for the case where the missing consideration of the Tx Fees caused an unexpected ADA loss.

Let's close this issue as duplicate and address the problem in the bug ticket:
- https://github.com/geniusyield/smart-order-router/issues/65
